[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000
solc = "0.8.24"
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink=lib/chainlink/contracts/src"
]

[fuzz]
runs = 100000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

[invariant]
runs = 256
depth = 32
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "preserve"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"

[etherscan]
avalanche = { key = "verifyContract" }
avalanche_fuji = { key = "verifyContract" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
